# Generated by Django 4.0.4 on 2022-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('acquired', models.BooleanField(default=False)),
                ('published_year', models.IntegerField()),
                ('thumbnail', models.URLField(null=True)),
                ('authors', models.ManyToManyField(to='bookstore.author')),
            ],
        ),
    ]
